services:
  postgres:
    image: 'postgres:16'
    platform: linux/amd64
    environment:
      - 'POSTGRES_DB=bookxchange'
      - 'POSTGRES_PASSWORD=amarn44m451QU3'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
